name:                advent-of-code
version:             0.1.0.0
github:              "bjing/advent-of-code"
license:             MIT
author:              "Brian Jing"
maintainer:          "example@example.com"
copyright:           "2021 Brian Jing"

extra-source-files:
- README.md

description:         Advent of Code Solutions 

dependencies:
- base

library:
  source-dirs: src

executables:
  advent-of-code-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - advent-of-code

tests:
  advent-of-code-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
    - base
    - hspec
